base_path: /mnt/x
model_path: ./ckpt/noisy_ostracods_net2_vit2_nuc.pt
class_img_path: class_images
base_learning_rate: 0.0001
batch_size: 256
epochs: 300
model: vit_b_16
co_model: vit_l_16
target: ostracods_genus_clean
classes: 79
weight: DEFAULT
criterion: CrossEntropyLoss
optimizer: SGD
momentum: 0.9
scheduler: steplr
step_size: 7
gamma: 0.1
workers: 16
device: '1'
FP16: 'True'
seed: 2024
fine_tune: 'False'
imgsz: 224
patience: 0.25
lambd: 0.1
forget_rate: 0.05
save_folder: ./ckpt
val: F
task: 'vanilla' # co_teaching, co_teaching_plus, mentor, vanilla